name: CI
on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main ]
permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm -r lint || pnpm -r lint --fix && git diff --quiet
      - name: Build
        run: pnpm -r build
      - name: Test
        run: pnpm -r test -- --ci --reporters=default --reporters=jest-junit
